[gcp_service_account]
type = "service_account"
project_id = "moonlit-buckeye-425823-h7"
private_key_id = "e99920be774cc65c7a11c8edbf75fa4a38de11a5"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDQDDi3dZ9Wu86L
6+eXj0OTZmvJ4RhAzReeAiEkcbKmvKGlPxkZDDiYl5YicqftbGN6prJGiZ0OsWGx
bFS/AoSACvh3RTOZwgHwx/jWcTIKxpBxP6UtawT3NDKUISOXWkD1yq46YDJlrH05
mCAjTZyR16+qUADd7NHA/MWHX5v+L8VDtwrSFnTSY58H5xsc9nmTZhFz6bZ2Sp4K
gSigqS/YAn6D3PTwBOtneM0XYYCvps7hxGzg9zXJm05F09u4gkYv5m0kMnTBA1wB
4VdGkQmZ4DBAl8AWqJnil+IDmJBA3lUsgaP/w6NLRVFAc+zXjfNfh0RUBBXTi87t
6WUwnOAlAgMBAAECggEAGSMo5S3Ok0283pYh1OOoABLTekB6zDWboWlTdNJSCihn
hY5Sq36ZBgLmzoG4/YxnlqW2i6RL+D8BdU0IDk4xEUGCFPMlEXJqBpw62joyGDA2
uqA8hnjUUEQbyl8YrExo5enX1FDUNgm51bAmTe2uOcbsQDFLcYUQMPe5rComsHcA
R1qPdUTAsqfR7NSh4nxkBoSVHvMMWwV7oHy6D6sLdwjLWOgfDqrYlnKSrEPol+/l
TVYfdcpX/ZCJ1yYi1fXAL3P1ArXcxwd76UMIfRjVH0orEBQKAgJELHduLlqC6QM8
rAslPM8gWJ/AVHJErdZkHCKP434xKr/e5G8oBEQGbwKBgQD1rfPFtht6+9FXqNYq
jqJLDk0qxXyxqyxMB9CvW7A1HBYiTQXoRhixvpw2HZBE1oklhsIYhXl8JfJMlcR5
iR2daR18WDp7KQyiZ+OqnqOvPM10mXP+E0zBplkPBLgPmH385xcZupUzpwE51KiL
vS0JAsSnr5yki1GakTHy4yiITwKBgQDYyZNlcbYEvHLeQ4ULKMHb0woz8o3z1Z1S
SUkEqSyKWswp++u5qjumdF6pu2tFhQLq3QpKA8m0yvjEJIskC4VfNFgxczZnQh7x
1JsYGS7DrChVc6sFZvDDkcDQ1ibkJolyE7tauzyG1HMh10UtFOmjVXsEjAZu4CAo
nneQYTNa/SwKBgQDg60t0417PPgGOzkycE48zRbmSAdFB2yMnzDPahweP59G/v2I8
Hwh2mbnrtS8iRoKyr2e9CV2KMjdcs/R3C/fn55cOArwviwo9GP2Oc8QJJ5I1QFO3
9TVdSIzaOgjEhmg5g9tbO71i129A4ZcYr62uRTGDDzxKTB3+cxUWd67g8wKBgCx0
UXxo7/lSp396ewrJxc8NHLeAUqmgsU0RaB7DjjWk3t7xIOqGxQqiLFND8oBkATAm
OZjp4+/l+1NFZx7yGdxnAHrLdGmCPpQ6k79CUrufTvoO6RAHhvGjrtVkRL9eQ6sX
7sBxSr0fTaiv2yiedDahLcPF7v/Hh/CsR/zPrO23AoGBANuAPicgbjiCFnmLk6nY
CLWGbwosHxjFmXC6oA7cdtgFKPukUyK9jAQaJ+YGyUoqdUS9bamo61ivcUGmDGo6
MkVLKarvXZoTHSKLFpcFF6Rtl8a/tfUkVkNHSPkj6DUvTUno8prOO5NyRG9uGmO9
75WqJLJI6sp+QFsjBTcf+4Hj
-----END PRIVATE KEY-----"""
client_email = "udemy-20241207@moonlit-buckeye-425823-h7.iam.gserviceaccount.com"
client_id = "108390177758731592839"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/udemy-20241207%40moonlit-buckeye-425823-h7.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

